// Date: 2016/04/17 21:51:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package strikerunit;

import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL12;

import cpw.mods.fml.client.FMLClientHandler;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.AdvancedModelLoader;

public class SUModelArmorS extends ModelBiped
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
  
  public SUModelArmorS()
  {
    textureWidth = 512;
    textureHeight = 256;
    
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(512, 256);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(512, 256);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(512, 256);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(512, 256);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(512, 256);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(512, 256);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      
      Shape1 = new ModelRenderer(this, 0, 34);
      Shape1.addBox(-2F, 3F, -3F, 5, 9, 6);
      Shape1.setRotationPoint(2F, 12F, 0F);
      Shape1.setTextureSize(512, 256);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 34);
      Shape2.addBox(-3F, 3F, -3F, 5, 9, 6);
      Shape2.setRotationPoint(-2F, 12F, 0F);
      Shape2.setTextureSize(512, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 50);
      Shape3.addBox(3F, 3F, -1F, 3, 4, 2);
      Shape3.setRotationPoint(2F, 12F, 0F);
      Shape3.setTextureSize(512, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 50);
      Shape4.addBox(-6F, 3F, -1F, 3, 4, 2);
      Shape4.setRotationPoint(-2F, 12F, 0F);
      Shape4.setTextureSize(512, 256);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 60);
      Shape5.addBox(-2F, 12F, -2F, 4, 5, 4);
      Shape5.setRotationPoint(2F, 12F, 0F);
      Shape5.setTextureSize(512, 256);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 60);
      Shape6.addBox(-2F, 12F, -2F, 4, 5, 4);
      Shape6.setRotationPoint(-2F, 12F, 0F);
      Shape6.setTextureSize(512, 256);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 20, 60);
      Shape7.addBox(-3F, 13F, -3F, 6, 1, 6);
      Shape7.setRotationPoint(2F, 12F, 0F);
      Shape7.setTextureSize(512, 256);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 20, 60);
      Shape8.addBox(-3F, 13F, -3F, 6, 1, 6);
      Shape8.setRotationPoint(-2F, 12F, 0F);
      Shape8.setTextureSize(512, 256);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
  }
  
  @Override
  public void render(Entity p_78088_1_, float p_78088_2_, float p_78088_3_, float p_78088_4_, float p_78088_5_, float p_78088_6_, float p_78088_7_)
  {
      this.setRotationAngles(p_78088_2_, p_78088_3_, p_78088_4_, p_78088_5_, p_78088_6_, p_78088_7_, p_78088_1_);
      /*
    head.render(p_78088_7_);
    body.render(p_78088_7_);
    rightarm.render(p_78088_7_);
    leftarm.render(p_78088_7_);
    rightleg.render(p_78088_7_);
    leftleg.render(p_78088_7_);
    */
      
      
      rightleg.render(p_78088_7_);
      leftleg.render(p_78088_7_);
    
    Shape1.render(p_78088_7_);
    Shape2.render(p_78088_7_);
    Shape3.render(p_78088_7_);
    Shape4.render(p_78088_7_);
    Shape5.render(p_78088_7_);
    Shape6.render(p_78088_7_);
    Shape7.render(p_78088_7_);
    Shape8.render(p_78088_7_);
    
    //GL11.glRotated(40F, 1.0F, 0.0F, 0.0F);
    this.bipedHead.render(p_78088_7_);
    this.bipedBody.render(p_78088_7_);
    this.bipedRightArm.render(p_78088_7_);
    this.bipedLeftArm.render(p_78088_7_);
    this.bipedRightLeg.render(p_78088_7_);
    this.bipedLeftLeg.render(p_78088_7_);
    this.bipedHeadwear.render(p_78088_7_);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  float iii;
  @Override
  public void setRotationAngles(float p_78087_1_, float p_78087_2_, float p_78087_3_, float p_78087_4_, float p_78087_5_, float p_78087_6_, Entity p_78087_7_)
  {
	  Minecraft minecraft = FMLClientHandler.instance().getClient();
      
	  //if (minecraft.thePlayer.moveForward > 0F) 
	  if(p_78087_7_.isSneaking())
      {
		  GL11.glRotated(40F, 1.0F, 0.0F, 0.0F);
		  
		  
    	  this.body.rotateAngleX = 0.6F;
    	  
    	  //this.rightleg.rotationPointZ = 7.0F;
    	  //this.rightleg.rotationPointY = 9.5F;
    	  this.rightleg.rotationPointZ = -1F;
    	  this.rightleg.rotationPointY = 11F;
    	  this.rightleg.rotateAngleZ = 0.3F;
    	  this.rightleg.rotateAngleX = 0.0F;
    	  this.rightleg.rotateAngleY = 0F;
    	  this.leftleg.rotationPointZ = -1F;
    	  this.leftleg.rotationPointY = 11F;
    	  this.leftleg.rotateAngleZ = -0.3F;
    	  this.leftleg.rotateAngleX = 0.0F;
    	  this.leftleg.rotateAngleY = 0F;
    	  
    	  this.Shape2.rotationPointZ = -1F;
    	  this.Shape2.rotationPointY = 11F;
    	  this.Shape2.rotateAngleZ = 0.3F;
    	  this.Shape2.rotateAngleX = 0.0F;
    	  this.Shape2.rotateAngleY = 0F;
    	  this.Shape4.rotationPointZ = -1F;
    	  this.Shape4.rotationPointY = 11F;
    	  this.Shape4.rotateAngleZ = 0.3F;
    	  this.Shape4.rotateAngleX = 0.0F;
    	  this.Shape4.rotateAngleY = 0F;
    	  this.Shape6.rotationPointZ = -1F;
    	  this.Shape6.rotationPointY = 11F;
    	  this.Shape6.rotateAngleZ = 0.3F;
    	  this.Shape6.rotateAngleX = 0.0F;
    	  this.Shape6.rotateAngleY = 0F;
    	  this.Shape8.rotationPointZ = -1F;
    	  this.Shape8.rotationPointY = 11F;
    	  this.Shape8.rotateAngleZ = 0.3F;
    	  this.Shape8.rotateAngleX = 0.0F;
    	  this.Shape8.rotateAngleY = 0F;
    	  
    	  this.Shape1.rotationPointZ = -1F;
    	  this.Shape1.rotationPointY = 11F;
    	  this.Shape1.rotateAngleZ = -0.3F;
    	  this.Shape1.rotateAngleX = 0.0F;
    	  this.Shape1.rotateAngleY = 0F;
    	  this.Shape3.rotationPointZ = -1F;
    	  this.Shape3.rotationPointY = 11F;
    	  this.Shape3.rotateAngleZ = -0.3F;
    	  this.Shape3.rotateAngleX = 0.0F;
    	  this.Shape3.rotateAngleY = 0F;
    	  this.Shape5.rotationPointZ = -1F;
    	  this.Shape5.rotationPointY = 11F;
    	  this.Shape5.rotateAngleZ = -0.3F;
    	  this.Shape5.rotateAngleX = 0.0F;
    	  this.Shape5.rotateAngleY = 0F;
    	  this.Shape7.rotationPointZ = -1F;
    	  this.Shape7.rotationPointY = 11F;
    	  this.Shape7.rotateAngleZ = -0.3F;
    	  this.Shape7.rotateAngleX = 0.0F;
    	  this.Shape7.rotateAngleY = 0F;
    	  
    	  if(iii < 360F){
          	this.Shape7.rotateAngleY = iii +0.6F;
          	this.Shape8.rotateAngleY = iii +0.6F;
   			iii = iii + 1F;
   		}else{
   			iii = 0F;
   		}
    //	  GL11.glRotated(-40F, 1.0F, 0.0F, 0.0F);
      }
	  else if(!p_78087_7_.onGround)
      {
    	  this.body.rotateAngleX = 0.6F;
    	  
    	  
    	  this.rightleg.rotationPointZ = 00F;
    	  this.rightleg.rotationPointY = 12F;
    	  this.rightleg.rotateAngleZ = 0.3F;
    	  this.rightleg.rotateAngleX = 0.0F;
    	  this.rightleg.rotateAngleY = 0F;
    	  this.leftleg.rotationPointZ = 0F;
    	  this.leftleg.rotationPointY = 12F;
    	  this.leftleg.rotateAngleZ = -0.3F;
    	  this.leftleg.rotateAngleX = 0.0F;
    	  this.leftleg.rotateAngleY = 0F;
    	  
    	  this.Shape2.rotationPointZ = 00F;
    	  this.Shape2.rotationPointY = 12F;
    	  this.Shape2.rotateAngleZ = 0.3F;
    	  this.Shape2.rotateAngleX = 0.0F;
    	  this.Shape2.rotateAngleY = 0F;
    	  this.Shape4.rotationPointZ = 00F;
    	  this.Shape4.rotationPointY = 12F;
    	  this.Shape4.rotateAngleZ = 0.3F;
    	  this.Shape4.rotateAngleX = 0.0F;
    	  this.Shape4.rotateAngleY = 0F;
    	  this.Shape6.rotationPointZ = 0F;
    	  this.Shape6.rotationPointY = 12F;
    	  this.Shape6.rotateAngleZ = 0.3F;
    	  this.Shape6.rotateAngleX = 0.0F;
    	  this.Shape6.rotateAngleY = 0F;
    	  this.Shape8.rotationPointZ = 0F;
    	  this.Shape8.rotationPointY = 12F;
    	  this.Shape8.rotateAngleZ = 0.3F;
    	  this.Shape8.rotateAngleX = 0.0F;
    	  this.Shape8.rotateAngleY = 0F;
    	  
    	  this.Shape1.rotationPointZ = 0F;
    	  this.Shape1.rotationPointY = 12F;
    	  this.Shape1.rotateAngleZ = -0.3F;
    	  this.Shape1.rotateAngleX = 0.0F;
    	  this.Shape1.rotateAngleY = 0F;
    	  this.Shape3.rotationPointZ = 0F;
    	  this.Shape3.rotationPointY = 12F;
    	  this.Shape3.rotateAngleZ = -0.3F;
    	  this.Shape3.rotateAngleX = 0.0F;
    	  this.Shape3.rotateAngleY = 0F;
    	  this.Shape5.rotationPointZ = 0F;
    	  this.Shape5.rotationPointY = 12F;
    	  this.Shape5.rotateAngleZ = -0.3F;
    	  this.Shape5.rotateAngleX = 0.0F;
    	  this.Shape5.rotateAngleY = 0F;
    	  this.Shape7.rotationPointZ = 0F;
    	  this.Shape7.rotationPointY = 12F;
    	  this.Shape7.rotateAngleZ = -0.3F;
    	  this.Shape7.rotateAngleX = 0.0F;
    	  this.Shape7.rotateAngleY = 0F;
    	  
    	  if(iii < 360F){
          	this.Shape7.rotateAngleY = iii +0.6F;
          	this.Shape8.rotateAngleY = iii +0.6F;
   			iii = iii + 1F;
   		}else{
   			iii = 0F;
   		}
      }else
      {
    	  
          this.body.rotateAngleX = 0F;
          
          this.bipedBody.rotateAngleX = 0F;
          this.bipedRightLeg.rotationPointZ = 0F;
    	  this.bipedRightLeg.rotationPointY = 12F;
    	  this.bipedRightLeg.rotateAngleZ = 0F;
    	  this.bipedRightLeg.rotateAngleX = 0F;
    	  this.bipedRightLeg.rotateAngleY = 0F;
    	  this.bipedLeftLeg.rotationPointZ = 0F;
    	  this.bipedLeftLeg.rotationPointY = 12F;
    	  this.bipedLeftLeg.rotateAngleZ = -0.0F;
    	  this.bipedLeftLeg.rotateAngleX = 0F;
    	  this.bipedLeftLeg.rotateAngleY = 0F;
        	  

        	  

              this.rightleg.rotationPointZ = 0F;
        	  this.rightleg.rotationPointY = 12F;
        	  this.rightleg.rotateAngleZ = 0F;
        	  this.rightleg.rotateAngleX = 0F;
        	  this.rightleg.rotateAngleY = 0F;
        	  this.leftleg.rotationPointZ = 0F;
        	  this.leftleg.rotationPointY = 12F;
        	  this.leftleg.rotateAngleZ = -0.0F;
        	  this.leftleg.rotateAngleX = 0F;
        	  this.leftleg.rotateAngleY = 0F;
        	  
        	  this.Shape2.rotationPointZ = 0F;
        	  this.Shape2.rotationPointY = 12F;
        	  this.Shape2.rotateAngleZ = 0F;
        	  this.Shape2.rotateAngleX = 0F;
        	  this.Shape2.rotateAngleY = 0F;
        	  this.Shape4.rotationPointZ = 0F;
        	  this.Shape4.rotationPointY = 12F;
        	  this.Shape4.rotateAngleZ = 0F;
        	  this.Shape4.rotateAngleX = 0F;
        	  this.Shape4.rotateAngleY = 0F;
        	  this.Shape6.rotationPointZ = 0F;
        	  this.Shape6.rotationPointY = 12F;
        	  this.Shape6.rotateAngleZ = 0F;
        	  this.Shape6.rotateAngleX = 0F;
        	  this.Shape6.rotateAngleY = 0F;
        	  this.Shape8.rotationPointZ = 0F;
        	  this.Shape8.rotationPointY = 12F;
        	  this.Shape8.rotateAngleZ = 0F;
        	  this.Shape8.rotateAngleX = 0F;
        	  this.Shape8.rotateAngleY = 0F;
        	  
        	  this.Shape1.rotationPointZ = 0F;
        	  this.Shape1.rotationPointY = 12F;
        	  this.Shape1.rotateAngleZ = -0F;
        	  this.Shape1.rotateAngleX = 0.F;
        	  this.Shape1.rotateAngleY = 0F;
        	  this.Shape3.rotationPointZ = 0F;
        	  this.Shape3.rotationPointY = 12F;
        	  this.Shape3.rotateAngleZ = -0F;
        	  this.Shape3.rotateAngleX = 0F;
        	  this.Shape3.rotateAngleY = 0F;
        	  this.Shape5.rotationPointZ = 0F;
        	  this.Shape5.rotationPointY = 12F;
        	  this.Shape5.rotateAngleZ = -0F;
        	  this.Shape5.rotateAngleX = 0F;
        	  this.Shape5.rotateAngleY = 0F;
        	  this.Shape7.rotationPointZ = 0F;
        	  this.Shape7.rotationPointY = 12F;
        	  this.Shape7.rotateAngleZ = -0F;
        	  this.Shape7.rotateAngleX = 0F;
        	  this.Shape7.rotateAngleY = 0F;
        	  
          this.rightleg.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F * p_78087_2_;
          this.leftleg.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F + (float)Math.PI) * 1.4F * p_78087_2_;
          this.rightleg.rotateAngleY = 0.0F;
          this.leftleg.rotateAngleY = 0.0F;
          //right
          this.Shape2.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F * p_78087_2_;
    	  this.Shape2.rotateAngleY = 0.0F;
    	  this.Shape4.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F * p_78087_2_;
    	  this.Shape4.rotateAngleY = 0.0F;
    	  this.Shape6.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F * p_78087_2_;
    	  this.Shape6.rotateAngleY = 0.0F;
    	  this.Shape8.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F * p_78087_2_;
    	  this.Shape8.rotateAngleY = 0.0F;
    	  //left
    	  this.Shape1.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F + (float)Math.PI) * 1.4F * p_78087_2_;
    	  this.Shape1.rotateAngleY = 0.0F;
    	  this.Shape3.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F + (float)Math.PI) * 1.4F * p_78087_2_;
    	  this.Shape3.rotateAngleY = 0.0F;
    	  this.Shape5.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F + (float)Math.PI) * 1.4F * p_78087_2_;
    	  this.Shape5.rotateAngleY = 0.0F;
    	  this.Shape7.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F + (float)Math.PI) * 1.4F * p_78087_2_;
    	  this.Shape7.rotateAngleY = 0.0F;
          }
      
      
      
      //if (minecraft.gameSettings.thirdPersonView == 1)
      {
      if ((minecraft.thePlayer.getEquipmentInSlot(1) != null)
				&& (minecraft.thePlayer.getEquipmentInSlot(1).getItem() instanceof SUItemArmorS)) {
    	  
    	  GL11.glTranslatef(0.5F, 0.0F, 0.0F);
    	  
      }
      }
      
      
      /*
      GL11.glPushMatrix();
      GL11.glEnable(GL12.GL_RESCALE_NORMAL);
      GL11.glTranslatef(0, 1F, 0);
		GL11.glRotatef(180F, 0.0F, 1.0F, 0.0F);
		GL11.glRotatef(180F, 1.0F, 0.0F, 0.0F);
		GL11.glScalef(0.3F, 0.3F, 0.3F);
      AdvancedModelLoader
		.loadModel(new ResourceLocation("strikerunit:textures/model/strikerunit.obj")).renderAll();
      
      GL11.glDisable(GL12.GL_RESCALE_NORMAL);
		GL11.glPopMatrix();
   */
  }

}
